### ISSUE TITLE
Docker Compose

### ISSUE THREAD

**Issue by olegdayo** [TVI-ARTEM/painter-react#1]
Create global Docker Compose for all 3 services something like that:
```yaml
services:
  painter_db:
    # TODO
    ports:
      - "5432:5432"
  painter_server:
    # TODO
    ports:
      - "3000:3000"
  painter:
    # TODO
    ports:
      - "80:80"
```
It'll let users to run app by using only one command
